# -*- coding: utf-8 -*-
"""KneeOA(P3)Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rb74hZ1hQieo9p2yqpHS4BhnrmDXjF3x
"""

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

import os

root_path = '/content/drive/MyDrive/Augmented_Dataset_Final'
total_files_grand = 0

print(f"Scanning for files in: {root_path}")
print("-" * 50)

for dirpath, dirnames, filenames in os.walk(root_path):
    if filenames:
        num_files_in_current_dir = len(filenames)
        print(f"Folder: {dirpath}, Number of files: {num_files_in_current_dir}")
        total_files_grand += num_files_in_current_dir

print("-" * 50)
print(f"Total files across all scanned folders: {total_files_grand}")

import os
import pandas as pd

def get_class_distribution(directory):
    """Gets the number of images in each subdirectory (class)."""
    class_counts = {}
    for subdir in os.listdir(directory):
        subdir_path = os.path.join(directory, subdir)
        if os.path.isdir(subdir_path):
            image_files = [f for f in os.listdir(subdir_path) if f.endswith(('jpg', 'jpeg', 'png'))]
            class_counts[subdir] = len(image_files)
    return class_counts

train_path = '/content/drive/MyDrive/Augmented_Dataset_Final/train'
valid_path = '/content/drive/MyDrive/Augmented_Dataset_Final/val'
test_path = '/content/drive/MyDrive/Augmented_Dataset_Final/test'

train_class_counts = get_class_distribution(train_path)
valid_class_counts = get_class_distribution(valid_path)
test_class_counts = get_class_distribution(test_path)

print("Training set class distribution:")
print(pd.DataFrame(list(train_class_counts.items()), columns=['Class', 'Count']))

print("\nValidation set class distribution:")
print(pd.DataFrame(list(valid_class_counts.items()), columns=['Class', 'Count']))

print("\nTest set class distribution:")
print(pd.DataFrame(list(test_class_counts.items()), columns=['Class', 'Count']))

import matplotlib.pyplot as plt
import pandas as pd


train_df = pd.DataFrame(list(train_class_counts.items()), columns=['Class', 'Count'])
valid_df = pd.DataFrame(list(valid_class_counts.items()), columns=['Class', 'Count'])
test_df = pd.DataFrame(list(test_class_counts.items()), columns=['Class', 'Count'])

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Plot training set distribution
axes[0].bar(train_df['Class'], train_df['Count'])
axes[0].set_title('Training Set Class Distribution')
axes[0].set_xlabel('Class')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)

# Plot validation set distribution
axes[1].bar(valid_df['Class'], valid_df['Count'])
axes[1].set_title('Validation Set Class Distribution')
axes[1].set_xlabel('Class')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=45)

# Plot testing set distribution
axes[2].bar(test_df['Class'], test_df['Count'])
axes[2].set_title('Test Set Class Distribution')
axes[2].set_xlabel('Class')
axes[2].set_ylabel('Count')
axes[2].tick_params(axis='x', rotation=45)


plt.tight_layout()
plt.show()

import os
import matplotlib.pyplot as plt
import random

def display_sample_images(directory, num_images=3):
    """Displays a few sample images from each subdirectory in the given directory."""
    for subdir in os.listdir(directory):
        subdir_path = os.path.join(directory, subdir)
        if os.path.isdir(subdir_path):
            print(f"Displaying sample images from: {subdir}")
            image_files = [f for f in os.listdir(subdir_path) if f.endswith(('jpg', 'jpeg', 'png'))]
            random.shuffle(image_files)
            for i in range(min(num_images, len(image_files))):
                img_path = os.path.join(subdir_path, image_files[i])
                img = plt.imread(img_path)
                plt.imshow(img)
                plt.title(subdir)
                plt.axis('off')
                plt.show()


train_path = '/content/drive/MyDrive/Augmented_Dataset_Final/train'
valid_path = '/content/drive/MyDrive/Augmented_Dataset_Final/val'


display_sample_images(train_path)
display_sample_images(valid_path)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Combine the dataframes by merging on the 'Class' column
all_counts_df = pd.merge(train_df, valid_df, on='Class', suffixes=('_Training', '_Validation'))
all_counts_df = pd.merge(all_counts_df, test_df, on='Class')
all_counts_df = all_counts_df.rename(columns={'Count': 'Count_Test'})
all_counts_df = all_counts_df.rename(columns={'Count_Training': 'Training', 'Count_Validation': 'Validation', 'Count_Test': 'Test'})
all_counts_df = all_counts_df.set_index('Class')

correlation_matrix = all_counts_df.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Class Distributions')
plt.show()

from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32

train_path = '/content/drive/MyDrive/Augmented_Dataset_Final/train'
val_path = '/content/drive/MyDrive/Augmented_Dataset_Final/val'
test_path = '/content/drive/MyDrive/Augmented_Dataset_Final/test'

loader = ImageDataGenerator(rescale=1./255)

train_ds = loader.flow_from_directory(train_path, target_size=IMAGE_SIZE, batch_size=BATCH_SIZE, class_mode='categorical')
valid_ds = loader.flow_from_directory(val_path, target_size=IMAGE_SIZE, batch_size=BATCH_SIZE, class_mode='categorical')
test_ds = loader.flow_from_directory(test_path, target_size=IMAGE_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False)

import tensorflow as tf
from tensorflow.keras import layers, models, Input

def se_block(input_feature, ratio=8):
    # Squeeze-and-Excitation: Helps model focus on the most important 'bone textures'
    channel_axis = -1
    filters = input_feature.shape[channel_axis]
    se_shape = (1, 1, filters)

    se = layers.GlobalAveragePooling2D()(input_feature)
    se = layers.Reshape(se_shape)(se)
    se = layers.Dense(filters // ratio, activation='relu', kernel_initializer='he_normal', use_bias=False)(se)
    se = layers.Dense(filters, activation='sigmoid', kernel_initializer='he_normal', use_bias=False)(se)

    return layers.Multiply()([input_feature, se])

def res_block_v3(x, filters):
    shortcut = x
    if x.shape[-1] != filters:
        shortcut = layers.Conv2D(filters, (1, 1), padding='same')(x)

    x = layers.SeparableConv2D(filters, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('swish')(x) # Swish often works better than ReLU for medical images

    x = layers.SeparableConv2D(filters, (3, 3), padding='same')(x)
    x = layers.BatchNormalization()(x)

    x = se_block(x) # Added Squeeze-Excitation here
    x = layers.Add()([x, shortcut])
    return layers.Activation('swish')(x)

def build_arnabsaha_v3():
    inputs = Input(shape=(224, 224, 3), name="ArnabSaha_v3_Input")

    # Entry Block
    x = layers.Conv2D(32, (3, 3), strides=2, padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('swish')(x)

    # Feature Extraction
    x = res_block_v3(x, 64)
    x = layers.MaxPooling2D(2, 2)(x)

    x = res_block_v3(x, 128)
    x = layers.MaxPooling2D(2, 2)(x)

    x = res_block_v3(x, 256)

    # Hybrid Global Pooling
    gap = layers.GlobalAveragePooling2D()(x)
    gmp = layers.GlobalMaxPooling2D()(x)
    x = layers.Concatenate()([gap, gmp])

    # Final Classifier
    x = layers.Dense(256, activation='swish')(x)
    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(3, activation='softmax')(x)

    return models.Model(inputs, outputs, name="ArnabSaha_v3")

model = build_arnabsaha_v3()
# We use a slightly smaller starting Learning Rate to avoid the early 'plateau'
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
              loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, EarlyStopping

rlr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=1e-7, verbose=1)
mcp = ModelCheckpoint('ArnabSaha_v3_Best.keras', save_best_only=True, monitor='val_accuracy')
es = EarlyStopping(monitor='val_accuracy', patience=12, restore_best_weights=True)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1),
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=30,
    callbacks=[rlr, mcp, es]
)

test_loss, test_acc = model.evaluate(test_ds)
print(f"Final Test Accuracy: {test_acc*100:.2f}%")
print(f"Final Validation Accuracy: {history.history['val_accuracy'][-1]*100:.2f}%")

import matplotlib.pyplot as plt

# Plot training & validation accuracy values
plt.figure(figsize=(10, 6))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

# Load best weights
model.load_weights('ArnabSaha_v3_Best.keras')

# Prediction
predictions = model.predict(test_ds)
y_pred = np.argmax(predictions, axis=1)
y_true = test_ds.classes

# Report
print(classification_report(y_true, y_pred, target_names=list(test_ds.class_indices.keys())))

# Confusion Matrix Visualization
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=test_ds.class_indices.keys(), yticklabels=test_ds.class_indices.keys())
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('ArnabSaha_v2 Confusion Matrix')
plt.show()